// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obfznlniwyojmfpuxcaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZnpubG5pd3lvam1mcHV4Y2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Nzg3NDksImV4cCI6MjA2NjI1NDc0OX0.E0aBWmOOpRopvgUt6CbDSJCGeKnRhI8dfmgV5ZIGBfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);